spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.132:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lsy152432

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml